### ISSUE TITLE
Complemento "Cálculos Previdenciários" indisponível

### ISSUE THREAD

**Issue by dvalentim** [Contadoria/CalculoRMI#12]
O programa complementar Cálculos Previdenciários não está funcionando dentro da planilha RMI.

**Comment by efujit** [comment]
Olá, Daniel.

Poderia enviar um print do erro?

Eric

Em qua, 23 de jan de 2019 às 17:28, daniel valentim <
notifications@github.com> escreveu:

**Comment by dvalentim** [comment]
Oi Eric,

ele não estava disponível... mas eu fechei o navegador e abri novamente aí rodou normalmente.

obrigado

**Comment by efujit** [comment]
Problema resolvido.
