### ISSUE TITLE
Não é possível criar novas planilhas

### ISSUE THREAD

**Issue by marcgtsr** [Contadoria/CalculoRMI#13]
Não aparecem os modelos quando vou criar uma planilha, não há modelos disponíveis (também não há mais um botão - planilhas da contadoria e sim documentos da contadoria, que é onde tento criar e ocorre esse erro). Estou reutilizando as planilhas que criei anteriormente, mas elas nao tem os dados atualizados.

**Comment by efujit** [comment]
Resolvido conforme comentário:
"O bug referido ao criar planilhas é apenas uma confusão de onde se clica para acessar as planilhas, só aparece quadno se clica em google drive, enquanto outros complementos aparecem com um clique com botão direito (no caso documentos da contadoria) que confundi achando que o nome tinha sido modificado por vcs."
