### ISSUE TITLE
Índice de limitação ao teto

### ISSUE THREAD

**Issue by cpanzica** [Contadoria/CalculoRMI#5]
Não está calculando o limitador ao teto

**Comment by cmlima** [comment]
Coloque o exemplo, por favor

Em 24 de mai de 2018, à(s) 17:18, cpanzica <notifications@github.com> escreveu:

**Comment by efujit** [comment]
Pelo que entendi, o fator não estava sendo calculado quando havia uma limitação do salário-de-benefício ao teto máximo.
Alterei a fórmula do intervalo `BaseIndiceTeto` para observar os valores `MediaComFatorPrevidenciario`e `MediaSemFatorPrevidenciario` em vez do próprio valor do `SalarioBeneficio`.
