### ISSUE TITLE
Indicação de concomitâncias

### ISSUE THREAD

**Issue by efujit** [Contadoria/CalculoRMI#9]
Sugestão de Mario Rodrigo do JEF/SBC: planilha poderia indicar os meses em que há salários de contribuição concomitantes para facilitar a visualização e ajustes posteriores.

**Comment by cmlima** [comment]
De minha parte, acho que a sugestão deve ser acolhida. 
Sugestão: criar coluna auxiliar em que a concomitância seria apontada e indicar visualmente a concomitância mediante formatação condicional. Um simples `CONT.NÚM(...) > =2` resolveria o problema. A questão é verificar como implementar isso por meio de uma `ARRAY_FORMULA`.

Em 19 de nov de 2018, à(s) 16:55, efujit <notifications@github.com> escreveu:

**Comment by efujit** [comment]
Verifiquei que as concomitâncias já estão sendo identificadas no intervalo `Concomitancia`.
Estou verificando a melhor forma de demonstração na aba `Salarios` mediante a formatação condicional.

**Comment by efujit** [comment]
Implementado em CalculoRMI v. 4.2.3.
